version: '3.3'

services:
  database_postgres_image:
    image: postgres
    container_name: bus-management-db
    environment: 
      POSTGRES_USER : user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: database_postgres_image
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "5432:5432"
  backend:
    container_name: bus-management-backend
    build: 
      context: ./backend
      dockerfile: ../docker/BackendDockerfile
    command: ./docker/backend_setup.sh
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: database_postgres_image
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - database_postgres_image

  frontend:
    container_name: bus-management-frontend
    build:
      context: ./frontend
      dockerfile: ../docker/FrontendDockerfile    
    command: ./docker/frontend_setup.sh
    ports:
      - "8080:8080"
    volumes:
     - .:/app
    networks:
      - app-network
    depends_on:
      - backend


networks:
    app-network:
        driver: bridge
