# Generated by Django 4.0.3 on 2022-04-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_drivers_age_alter_journeys_assigned_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='bus_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='driver_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journeys',
            name='journey_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='passenger_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
