# Generated by Django 4.0.3 on 2022-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_drivers_age_alter_drivers_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeys',
            name='from_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='journeys',
            name='to_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
