# Generated by Django 4.0.3 on 2022-04-05 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_journeys_assigned_driver_alter_journeys_assigned_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='assigned_journey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.journeys'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journeys',
            name='assigned_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.buses'),
        ),
        migrations.AlterField(
            model_name='journeys',
            name='assigned_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.drivers'),
        ),
    ]
