# Generated by Django 4.0.3 on 2022-04-06 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_passengers_assigned_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeys',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 6, 0, 2, 14, 220106)),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='assigned_journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.journeys'),
        ),
    ]
