# Generated by Django 4.0.3 on 2022-04-06 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_journeys_date_alter_passengers_assigned_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeys',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 6, 0, 3, 10, 508390, tzinfo=utc)),
        ),
    ]
