# Generated by Django 4.0.3 on 2022-04-06 00:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_journeys_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeys',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 6, 0, 5, 44, 500062, tzinfo=utc)),
        ),
    ]
