# Generated by Django 4.0.3 on 2022-04-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_journeys_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeys',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
