# Generated by Django 4.0.3 on 2022-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_buses_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeys',
            name='assigned_bus',
        ),
        migrations.AddField(
            model_name='journeys',
            name='buses',
            field=models.ManyToManyField(to='backend.buses'),
        ),
    ]
