# Generated by Django 4.0.3 on 2022-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_journeys_assigned_driver_buses_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='has_assigned_bus',
            field=models.BooleanField(default=False),
        ),
    ]
