# Generated by Django 4.0.3 on 2022-04-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_journeys_buses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeys',
            name='buses',
            field=models.ForeignKey(default=1, null=None, on_delete=django.db.models.deletion.CASCADE, to='backend.buses'),
        ),
    ]
