# Generated by Django 4.0.3 on 2022-04-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_journeys_buses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeys',
            old_name='buses',
            new_name='bus',
        ),
    ]
