# Generated by Django 4.0.3 on 2022-04-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_remove_journeys_bus_journeys_buses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeys',
            name='buses',
            field=models.ManyToManyField(to='backend.buses'),
        ),
    ]
