# Generated by Django 4.0.3 on 2022-04-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_rename_assigned_journey_passengers_journey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.drivers'),
        ),
    ]
